PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Folder" (
	"Id"	INTEGER NOT NULL,
	"Path"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Exclude" (
	"Id"	INTEGER NOT NULL,
	"Pattern"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
